version: '2.4'
services:
    pnm:
        image: docsis-pnm
        ports:
            - 127.0.0.1:8080:8080
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:12-alpine
        volumes:
            - db:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
        environment:
            - POSTGRES_PASSWORD=insecurepassword
            - POSTGRES_USER=docsispnm

volumes:
    db:
