name: Docker Image CI

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        tag=${{ github.repository }}:$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file Dockerfile --tag $tag
        docker save "$tag" | gzip > "${tag}.tgz"
      
    - name: upload container image
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.repository }} container image
        path: ${{ github.repository }}*.tgz
