name: Docker Image CI

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docsis-pnm

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        tag=${{ env.IMAGE_NAME }}:$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file Dockerfile --tag $tag
        docker save "$tag" | gzip > "${tag}.tgz"
      
    - name: upload container image
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.IMAGE_NAME }} container image
        path: ${{ env.IMAGE_NAME }}*.tgz
