name: Docker Image CI

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docsis-pnm

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Packages Container registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push the container image
      run: |
        export tag=${{ env.IMAGE_NAME }}:$(git rev-parse --short "$GITHUB_SHA")
        # tag_clean=$(tr : _ <<<"$tag")
        docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ github.actor }}/$tag
        # docker save "$tag" | gzip > "${tag_clean}.tgz"
        docker push ${{ env.REGISTRY }}/${{ github.actor }}/$tag
      
